### ISSUE TITLE
Labels are not backuped / restored

### ISSUE THREAD

**Issue by col-panic** [loomchild/volume-backup#33]
When restoring a volume backup, its associated Labels are lost.

**Comment by loomchild** [comment]
Interesting, thanks for reporting!

However, I am afraid I won't be able to recover the volumes, since the restored volume is created automatically by Docker or manually before the restore operation. Also, it's not possible to update labels once the volume has been created, which complicates matters even further. It might even not be desired to recover the same labels IMHO, and maybe better set them manually. Perhaps what I can do is to store the volume labels in a file inside the archive, to be restored manually.

What do you think? Do you have an idea how it could be done?

**Comment by col-panic** [comment]
Inspecting the volume shows that there is not too much data being stored with a volume
```
marco@Marcos-MBP-2019 ~> docker volume inspect elexis-environment_solr_data
[
    {
        "CreatedAt": "2020-11-24T09:50:35Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "elexis-environment",
            "com.docker.compose.version": "1.27.4",
            "com.docker.compose.volume": "solr_data"
        },
        "Mountpoint": "/var/lib/docker/volumes/elexis-environment_solr_data/_data",
        "Name": "elexis-environment_solr_data",
        "Options": null,
        "Scope": "local"
    }
]
```

I think you could simply create a file next to the backup file that contains just this data (this would even be good for backup metadata purposes I guess). On restore there could be a flag to also restore the labels (if the metadata file is available).

For me it is important due to the usage of docker-compose which places the labels to associate them with a project - now on restore this association gets lost. 

As your program runs as a docker container - are the labels visible within this container or would this have to happen "outside" (that is as execution parameter)?

**Comment by col-panic** [comment]
An adjacent metadata file would even allow me to "fix" existing backups, by simply creating the file with the resp. values which then would be restored :)

**Comment by col-panic** [comment]
It seems like we have to create the volumes manually before using restore in order for the labels to be available

Showing the labels of existing volume in  json format

```
docker inspect elexis-environment_bookstack_storage_uploads -f "{{json .Labels}}"
{"com.docker.compose.project":"elexis-environment","com.docker.compose.version":"1.26.2","com.docker.compose.volume":"bookstack_storage_uploads"}
```

Creating a volume with these labels
```
docker volume create --label "com.docker.compose.project"="elexis-environment"  --label "com.docker.compose.version"="1.26.2"  --label "com.docker.compose.volume"="bookstack_storage_uploads" elexis-environment_bookstack_storage_uploads
```

**Comment by loomchild** [comment]
Thanks for suggestions and sorry for delay - I will try to work on this next week.

**Comment by loomchild** [comment]
(first sorry for delay, I was very busy over the last few months working on other projects)

Yeah, you are right that the restore operation would need to be manual, since my script is not creating the volume itself. Also, as I mentioned earlier, it might not be always desired to restore the labels.

As for storing the volume labels in a separate file (or better in the backup archive, as this will avoid interfering with recommended backup-to-stdout method), I don't know how can I do it, since I am interacting with the already mounted volume from within Docker in my script. In other words, I can't call `docker volume inspect` in my script, since there's no docker installed inside my container. 

What I can do is to document what you described in README as a best practice, so others can back-up their volume metadata manually if required.

**Comment by col-panic** [comment]
I think that an addition to the README is already a very good step! I managed to re-create the labels relevant for me via docker-volume create.

You should maybe also point out, that  docker-compose keeps the "connection" to the volumes using labels. So in a docker-compose backup/restore scenario this seems to be mandatory! 

Thanks for you work!

**Comment by loomchild** [comment]
Great, thanks for info - I will add it soon to the README.

**Comment by loomchild** [comment]
Done, added the text to README. Feel free to review / suggest improvements. Thanks for your help.
