### ISSUE TITLE
Permissions of the volume itself not correctly restored

### ISSUE THREAD

**Issue by breucode** [loomchild/volume-backup#4]
When you backup a volume (for example /etc/foo) and this folder has the chmod permissions 700, the folder has different permissions after restoration.

This becomes evident, when backing up a postgres volume, as postgresl won't start when the folder has wrong permissions.

**Comment by loomchild** [comment]
Thanks for reporting an issue.

I just tested it and it seems to preserve the permissions of the archived files correctly. Could you please describe precisely, step by step how to reproduce the problem? Are you talking about changing permissions for the mounted directory itself (it that case it's managed by Docker AFAIK)?

**Comment by breucode** [comment]
Sorry for the late reply.

To reproduce the issue, you can do the following:
1. 
```
docker run -d --name openproject -e SECRET_KEY_BASE=secret \
  -v pgdata:/var/lib/postgresql/9.4/main \
  openproject/community:7
```
Watch the logs until you see the success message. That is the time, when the internal Postgres Server is successfully configured.

2. Shutdown the server and delete the openproject container.
3. Backup the pgdata volume.
4. Delete the pgdata volume on docker.
5. Restore the pgdata volume.
6. Start the openproject container with the same command as step 1.

When you watch the logs of the container, it doesn't start up because the permissions of the /var/lib/postgresql/9.4/main are not 700 any more.

When I mounted the pgdata volume in a debian image (mountpoint /pgadata/ and executed chmod 700 /pgdata and started the openproject container again, it worked.

**Comment by loomchild** [comment]
Thanks a lot for detailed description.

Since you are mounting the volume directly on /var/lib/postgresql/9.4/main, I think Docker is directly responsible for setting the permissions on the new one and volume-backup is not really touching it - it only recovers contents of the volume, not the volume itself. 

Still it's an interesting and probably common use case, I will investigate and try to do something about it. 

Could you clarify how do you create the deleted volume?

**Comment by breucode** [comment]
I restored the image with the following command:

`docker run -v pgdata:/volume -v /home/USER:/backup --rm loomchild/volume-backup restore pgdata`

**Comment by loomchild** [comment]
Still no time to look into this, sorry.. 

In the meantime, I found this, perhaps it can serve as a workaround: https://github.com/lebokus/docker-volume-bindfs

**Comment by loomchild** [comment]
Hi,

I finally managed to closer at the problem (sorry for a long wait) and I think it's not related to `volume-backup` at all. The script properly recovers permissions, also for the volume root directory.

I can reproduce the issue by simply running, stopping, deleting and re-running the `openproject` container (it corresponds to points 1, 2 and 6 in your reproduction path).  At the moment I try to start it again, permissions change. 

I think the issue is caused by a bug in https://github.com/opf/openproject/blob/dev/Dockerfile.public. This line seems to be responsible:

    RUN rm -rf /var/lib/postgresql/9.6/main && mkdir -p /var/lib/postgresql/9.6/main && chown -R postgres:postgres /var/lib/postgresql/9.6

When I tried a simple test and included a similar line, it refreshed the permissions every time the container was created. Specifically `mkdir` seems to be causing an issue here.

Please let me know if you would like to continue investigating this issue, otherwise I will close the ticket. I will also contact the project about the issue.

Jarek
