### ISSUE TITLE
Slow zstd compression

### ISSUE THREAD

**Issue by pschonmann** [loomchild/volume-backup#46]
Ive upgraded to debian11 and backups of images are now slow.
I dont know if its caused by #45 or something else. But zstd doesnt run with multithread option -T0

Tried to
```
env ZSTD_NBTHREADS=$(nproc) docker run --log-driver none -v $i:/volume --rm loomchild/volume-backup backup -c zstd > $BACKUP_DIR/volume-$i-$DATE.tar.zst
```

Not all cores used. Seems only one is running.
Tried to pass with -x '-T0'
Getting
```
tar: 0: Cannot stat: No such file or directory
tar: Error is not recoverable: exiting now
```

Probably function workaround now for me is:
```
docker run --log-driver none -v $i:/volume --rm loomchild/volume-backup backup -c 0 | zstd -T0 > $BACKUP_DIR/volume-$i-$DATE.tar.zst
```

**Comment by loomchild** [comment]
Hi,

Thanks for reporting this. It shouldn't be related to your upgrade to Debian 11, since everything is running in container.

The issue might be related to using `zstd --adapt`, since on the [man page](https://manpages.debian.org/unstable/zstd/zstd.1.en.html) I found:

> note : at the time of this writing, --adapt can remain stuck at low speed when combined with multiple worker threads (>=2).

Can you please try to run like this and see if it helps:

```
env ZSTD_NBTHREADS=$(nproc) docker run --log-driver none -v $i:/volume --rm loomchild/volume-backup backup -c none -x '-I zstd' > $BACKUP_DIR/volume-$i-$DATE.tar.zst
```

If it does, I will revert the `--adapt` setting.

**Comment by loomchild** [comment]
I was finally able to test it and indeed `zstd` was slower due to `--adapt` options. I have reverted it, now it should be faster with the original setting.
