### ISSUE TITLE
why not back up When you need to back up /var/lib/docker/volumes/<volume-name>?

### ISSUE THREAD

**Issue by jadster** [loomchild/volume-backup#6]
Remind me why we can't just back up or restore to folder 

`/var/lib/docker/volumes/<volume-name>` ?

**Comment by loomchild** [comment]
Regarding simply grabbing contents of /var/lib/docker/volumes/<volume>/_data directory – this could work, but I needed to talk to a remote Docker daemon and storing the backup on another volume, so this solution was more convenient. 

I was also worried to build a solution on implementation detail (directory location) and about preserving file permissions, but maybe for no good reason. 

I also think it's more convenient to operate on volumes (and their names instead of ids) and using a Docker-based tool being already in Docker world, but in the end it's just a simple wrapper script around a tar command with some nice extras (reading from stding / writing to stdout for example). 

More infos / reasoning: https://loomchild.net/2017/03/26/backup-restore-docker-named-volumes/,
