### ISSUE TITLE
Should warn if volume name was mistyped

### ISSUE THREAD

**Issue by tuukka** [loomchild/volume-backup#9]
I noticed that if I have a typo in the volume name, volume-backup will complete but the backup will be empty. Could backup (and restore) warn (or even die) if the volume is empty (newly created)?

**Comment by loomchild** [comment]
Hi, you are totally right. As the utility is more and more widely used (it started as internal tool for Puffin), basic protections/validations need to be added. I will do it ASAP (I am very busy for another ~10days,  will try to address it afterwards). Feel free to propose a PR in the meantime if you can.

**Comment by loomchild** [comment]
Hi again,

I added a check that verifies whether the volume is empty and fails. I can't really check if volume exists because it's `docker` who creates it automatically if it's missing.

In addition I realized that I am outputting error to `stdout` so they are not visible when redirecting the output to archive. I changed it to stderr, so they are always visible. 

I am closing this issue, but please let me know if you think this solution is not good or you have other idea, then I can re-open it.

**Comment by tuukka** [comment]
This is perfect for me - thank you!
